Connect-ExchangeOnline

$OWAParameters = @(
"WacEditingEnabled",
"PrintWithoutDownloadEnabled",
"OneDriveAttachmentsEnabled",
"ThirdPartyFileProvidersEnabled ",
"AdditionalStorageProvidersAvailable",
"ClassicAttachmentsEnabled",
"ReferenceAttachmentsEnabled",
"SaveAttachmentsToCloudEnabled",
"InternalSPMySiteHostURL",
"ExternalSPMySiteHostURL",
"ExternalImageProxyEnabled",
"NpsSurveysEnabled",
"MessagePreviewsDisabled",
"PersonalAccountCalendarsEnabled",
"TeamsnapCalendarsEnabled",
"BookingsMailboxCreationEnabled",
"BookingsMailboxDomain",
"ProjectMocaEnabled",
"DirectFileAccessOnPublicComputersEnabled",
"DirectFileAccessOnPrivateComputersEnabled",
"WebReadyDocumentViewingOnPublicComputersEnabled",
"WebReadyDocumentViewingOnPrivateComputersEnabled",
"ForceWebReadyDocumentViewingFirstOnPublicComputers",
"ForceWebReadyDocumentViewingFirstOnPrivateComputers",
"WacViewingOnPublicComputersEnabled",
"WacViewingOnPrivateComputersEnabled",
"ForceWacViewingFirstOnPublicComputers",
"ForceWacViewingFirstOnPrivateComputers",
"ActionForUnknownFileAndMIMETypes",
"WebReadyFileTypes",
"WebReadyMimeTypes",
"WebReadyDocumentViewingForAllSupportedTypes",
"WebReadyDocumentViewingSupportedMimeTypes",
"WebReadyDocumentViewingSupportedFileTypes",
"AllowedFileTypes",
"AllowedMimeTypes",
"ForceSaveFileTypes",
"ForceSaveMimeTypes",
"BlockedFileTypes",
"BlockedMimeTypes",
"FeedbackEnabled",
"SMimeSuppressNameChecksEnabled",
"EmptyStateEnabled",
"BizBarEnabled",
"AccountTransferEnabled",
"OfflineEnabledWeb",
"OfflineEnabledWin",
"OneWinNativeOutlookEnabled",
"PersonalAccountsEnabled",
"AdditionalAccountsEnabled",
"ChangeSettingsAccountEnabled",
"ItemsToOtherAccountsEnabled",
"AllowedOrganizationAccountDomains",
"HideClassicOutlookToggleOut",
"OutlookDataFile",
"PhoneticSupportEnabled",
"DefaultTheme",
"IsDefault",
"DefaultClientLanguage",
"LogonAndErrorLanguage",
"UseGB18030",
"UseISO885915",
"OutboundCharset",
"GlobalAddressListEnabled",
"OrganizationEnabled",
"ExplicitLogonEnabled",
"OWALightEnabled",
"DelegateAccessEnabled",
"IRMEnabled",
"CalendarEnabled",
"ContactsEnabled",
"TasksEnabled",
"JournalEnabled",
"NotesEnabled",
"OnSendAddinsEnabled",
"RemindersAndNotificationsEnabled",
"PremiumClientEnabled",
"SpellCheckerEnabled",
"SearchFoldersEnabled",
"SignaturesEnabled",
"ThemeSelectionEnabled",
"JunkEmailEnabled",
"UMIntegrationEnabled",
"WSSAccessOnPublicComputersEnabled",
"WSSAccessOnPrivateComputersEnabled",
"ChangePasswordEnabled",
"UNCAccessOnPublicComputersEnabled",
"UNCAccessOnPrivateComputersEnabled",
"ActiveSyncIntegrationEnabled",
"AllAddressListsEnabled",
"RulesEnabled",
"PublicFoldersEnabled",
"SMimeEnabled",
"RecoverDeletedItemsEnabled",
"InstantMessagingEnabled",
"TextMessagingEnabled",
"ForceSaveAttachmentFilteringEnabled",
"SilverlightEnabled",
"InstantMessagingType",
"DisplayPhotosEnabled",
"SetPhotoEnabled",
"AllowOfflineOn",
"SetPhotoURL",
"PlacesEnabled",
"WeatherEnabled",
"LocalEventsEnabled",
"InterestingCalendarsEnabled",
"AllowCopyContactsToDeviceAddressBook",
"PredictedActionsEnabled",
"UserDiagnosticEnabled",
"FacebookEnabled",
"LinkedInEnabled",
"WacExternalServicesEnabled",
"WacOMEXEnabled",
"ReportJunkEmailEnabled",
"GroupCreationEnabled",
"SkipCreateUnifiedGroupCustomSharepointClassification",
"WebPartsFrameOptionsType",
"UserVoiceEnabled",
"SatisfactionEnabled",
"FreCardsEnabled",
"ConditionalAccessPolicy",
"ConditionalAccessFeature",
"OutlookBetaToggleEnabled",
"ShowOnlineArchiveEnabled",
"OutlookNewslettersAccessLevel",
"OutlookNewslettersReactions",
"OutlookNewslettersShowMore",
"AdminDisplayName"
)

$mailbox1 = "OwaMailboxPolicy-Default"
$mailbox2 = "BlockExternalEmail-Policy"

foreach($parameter in $OWAParameters){
    $mailbox1ParameterValue = Get-OwaMailboxPolicy -Identity $mailbox1 | Select-Object -ExpandProperty $parameter
    $mailbox2ParameterValue = Get-OwaMailboxPolicy -Identity $mailbox2 | Select-Object -ExpandProperty $parameter

    if($mailbox1ParameterValue -ne $mailbox2ParameterValue){
        Write-Host "Check " $parameter
        #$updateParameter = "-" + $parameter
        #Set-OwaMailboxPolicy -Identity "BlockExternal-Policy" $updateParameter, $mailbox1ParameterValue
    }
}
